Explore organizations
credebl/adeya-wallet pull request #117
Opened 2023-10-30 14:29 UTC by poonam-ghewande

### Summary 

1. Added explore organization, details with available credential and connection
2. Update loader in application
3. Update connection flow

### Issue ticket number and link    
add ticket link

### Checklist before requesting a review
- [x]  All commits contain a DCO Signed-off-by line (we use the DCO GitHub app to enforce this).
- [x]  Self-review of code & No unnecessary commented-out code.
- [x]  All existing functionality remain intact.
- [x]  Updated the README if necessary..
- [x]  No hard-coded sensitive information.

2023-11-01 07:28 UTC, sairanjit requested changes

2023-11-01 07:28 UTC, sairanjit commented on app/components/common/AlphabetFlatList.tsx
> +  // const [selectAlphabet, setSelectAlphabet] = useState('')
Remove commented code

2023-11-01 07:28 UTC, sairanjit commented on app/components/common/AlphabetFlatList.tsx
> +    // setSelectAlphabet(titles[0])
Remove commented code

2023-11-01 07:28 UTC, sairanjit commented on app/components/common/AlphabetFlatList.tsx
> +      {/* {props.renderSectionHeader && props.renderSectionHeader({ title: info.item })} */}
Remove commented code

2023-11-01 07:28 UTC, sairanjit commented on app/components/common/AlphabetListView.tsx
> +class AlphabetListView extends PureComponent<IProps, State> {
Convert this component to functional component

2023-11-01 07:28 UTC, sairanjit commented on app/components/common/ScanButton.tsx
> +const ScanButton: React.FC<Props> = () => {
`Props` where is the props values used from ?

2023-11-01 07:28 UTC, sairanjit commented on app/components/common/SectionHeader.tsx
> +const SectionHeader: FC<IProps> = function () {
```suggestion
const SectionHeader: FC<IProps> = () => {
```suggestion
const SectionHeader: FC<IProps> = function () {
```
```

2023-11-01 07:28 UTC, sairanjit commented on app/components/common/SectionListItem.tsx
> +            backgroundColor: props.active ? '#1F4EAD' : 'transparent',
Move colors to theme

2023-11-01 07:28 UTC, sairanjit commented on app/components/common/SectionListItem.tsx
> +const SectionListItem: FC<IProps> = function (props) {
Use arrow function syntax

2023-11-01 07:28 UTC, sairanjit commented on app/components/common/SectionListItem.tsx
> +              color: props.active ? 'white' : '#333',
Use colors from theme

2023-11-01 07:28 UTC, sairanjit commented on app/components/common/styles.ts
> +    backgroundColor: '#F4F4F4',
Use colors from theme

2023-11-01 07:28 UTC, sairanjit commented on app/components/common/styles.ts
> +    fontFamily: 'PingFangSC-Regular',
Use font family from theme

2023-11-01 07:28 UTC, sairanjit commented on app/defaultConfiguration.ts
> +import { Config } from 'react-native-config'
Is it a default import?

2023-11-01 07:28 UTC, sairanjit commented on app/navigators/CredentialStack.tsx
> +  const { scan } = useConfiguration()
Use `Scan` component directly from screens

2023-11-01 07:28 UTC, sairanjit commented on app/navigators/HomeStack.tsx
> +      <Stack.Screen name={Screens.Scan} component={scan} />
Use `Scan` component directly from screens

2023-11-01 07:28 UTC, sairanjit commented on app/localization/en/index.ts
>      "Organization": "Explore",
Please use proper key values for localization `"Organization": "Explore"`

2023-11-01 07:28 UTC, sairanjit commented on app/navigators/TabStack.tsx
> -          listeners={({ navigation }) => ({
Please verify if we use `assertConnectedNetwork` while using scan screen beacuse that helps us in restricting user to scan qrcodes if device is not connected to internet

2023-11-01 07:28 UTC, sairanjit commented on app/screens/ContactItem.tsx
> +        <Text>{`${item.name}`}</Text>
Use colors from theme

2023-11-01 07:28 UTC, sairanjit commented on app/screens/ListCredentials.tsx
> +      <View style={{ justifyContent: 'flex-end', marginTop: '90%' }}>
Avoid inline styles

2023-11-01 07:28 UTC, sairanjit commented on app/screens/OrganizationDetails.tsx
> +  logoUrl: any
LogoUrl is string here

2023-11-01 07:28 UTC, sairanjit commented on app/screens/OrganizationList.tsx
> +import { ScaledSheet } from 'react-native-size-matters'
Please use `react-native-responsive-screen`

2023-11-01 07:28 UTC, sairanjit commented on app/screens/OrganizationList.tsx
> +      borderColor: '#E1EAFF',
Use colors from theme

2023-11-01 07:28 UTC, sairanjit commented on app/screens/OrganizationList.tsx
> +  const fetchData = async () => {
convert this to hooks

2023-11-01 07:28 UTC, sairanjit commented on app/screens/OrganizationList.tsx
> +  const filteredOrganizations = orgnizationdata.organizations.filter(org => {
`orgnizationdata` please check spelling and prefer using camelCase

2023-11-01 07:28 UTC, sairanjit commented on app/screens/OrganizationList.tsx
> +        <Text style={styles.titleText}>Select an organization to get credentials</Text>
Add text to localizations

2023-11-01 07:28 UTC, sairanjit commented on app/utils/Organization.ts
> +    const response = await fetch('https://devapi.credebl.id/orgs/public-profile')
Add urls to `.env`

2023-11-01 07:28 UTC, sairanjit commented on package.json
> +    "react-native-size-matters": "^0.4.2",
Please use this package `react-native-responsive-screen`

2023-11-01 13:10 UTC, poonam-ghewande commented on app/components/common/AlphabetFlatList.tsx
> +  // const [selectAlphabet, setSelectAlphabet] = useState('')
removed

2023-11-01 13:10 UTC, poonam-ghewande commented on app/components/common/AlphabetFlatList.tsx
> +      {/* {props.renderSectionHeader && props.renderSectionHeader({ title: info.item })} */}
removed

2023-11-01 13:12 UTC, poonam-ghewande commented on app/screens/OrganizationDetails.tsx
> +  logoUrl: any
added string

2023-11-01 13:13 UTC, poonam-ghewande commented on app/screens/OrganizationList.tsx
> +      borderColor: '#E1EAFF',
added  color in theme

2023-11-01 13:13 UTC, poonam-ghewande commented on app/screens/OrganizationList.tsx
> +        <Text style={styles.titleText}>Select an organization to get credentials</Text>
Added to localizations

2023-11-02 11:57 UTC, poonam-ghewande commented on app/screens/OrganizationList.tsx
> +  const filteredOrganizations = orgnizationdata.organizations.filter(org => {
done

2023-11-02 11:58 UTC, poonam-ghewande commented on app/components/common/AlphabetFlatList.tsx
> +    // setSelectAlphabet(titles[0])
done

2023-11-02 11:58 UTC, poonam-ghewande commented on app/components/common/AlphabetFlatList.tsx
> +      {/* {props.renderSectionHeader && props.renderSectionHeader({ title: info.item })} */}
done

2023-11-02 11:59 UTC, poonam-ghewande commented on app/components/common/ScanButton.tsx
> +const ScanButton: React.FC<Props> = () => {
removed it was unused.

2023-11-02 11:59 UTC, poonam-ghewande commented on app/components/common/SectionListItem.tsx
> +const SectionListItem: FC<IProps> = function (props) {
done

2023-11-02 12:00 UTC, poonam-ghewande commented on app/components/common/SectionListItem.tsx
> +            backgroundColor: props.active ? '#1F4EAD' : 'transparent',
done

2023-11-02 12:00 UTC, poonam-ghewande commented on app/components/common/SectionListItem.tsx
> +              color: props.active ? 'white' : '#333',
done

2023-11-02 12:00 UTC, poonam-ghewande commented on app/components/common/styles.ts
> +    backgroundColor: '#F4F4F4',
done

2023-11-02 12:00 UTC, poonam-ghewande commented on app/components/common/styles.ts
> +    fontFamily: 'PingFangSC-Regular',
done

2023-11-02 12:00 UTC, poonam-ghewande commented on app/localization/en/index.ts
>      "Organization": "Explore",
done

2023-11-02 12:01 UTC, poonam-ghewande commented on app/navigators/CredentialStack.tsx
> +  const { scan } = useConfiguration()
done

2023-11-02 12:01 UTC, poonam-ghewande commented on app/navigators/TabStack.tsx
> -          listeners={({ navigation }) => ({
verified and done

2023-11-02 12:01 UTC, poonam-ghewande commented on app/screens/ContactItem.tsx
> +        <Text>{`${item.name}`}</Text>
done

2023-11-02 12:02 UTC, poonam-ghewande commented on app/screens/OrganizationDetails.tsx
> +  logoUrl: any
done

2023-11-02 12:02 UTC, poonam-ghewande commented on app/screens/OrganizationList.tsx
> +import { ScaledSheet } from 'react-native-size-matters'
done

2023-11-02 12:02 UTC, poonam-ghewande commented on app/screens/OrganizationList.tsx
> +  const fetchData = async () => {
done

2023-11-02 12:03 UTC, poonam-ghewande commented on app/utils/Organization.ts
> +    const response = await fetch('https://devapi.credebl.id/orgs/public-profile')
done

2023-11-02 12:03 UTC, poonam-ghewande commented on package.json
> +    "react-native-size-matters": "^0.4.2",
done

2023-11-02 12:04 UTC, poonam-ghewande commented on app/components/common/AlphabetListView.tsx
> +class AlphabetListView extends PureComponent<IProps, State> {
done

2023-11-02 12:05 UTC, poonam-ghewande commented on app/components/common/SectionHeader.tsx
> +const SectionHeader: FC<IProps> = function () {
done

2023-11-02 13:52 UTC, sairanjit approved these changes

2023-11-02 13:52 UTC, sairanjit commented on app/components/common/AlphabetListView.tsx
> +const AlphabetListView: React.FC<IProps> = props => {
`IProps` where is this import used from ?

2023-11-02 13:52 UTC, sairanjit commented on app/components/common/AlphabetListView.tsx
> +  const initData = ({ titles, contentHeight }: IProps) => {
`IProps` where is this import used from ?

2023-11-02 13:52 UTC, sairanjit commented on app/components/common/AlphabetListView.tsx
> +    const event: any = e.nativeEvent || {}
Here `any` can be typed

2023-11-02 13:52 UTC, sairanjit commented on app/components/common/SectionHeader.tsx
> +  title: string
Where is the `title` prop used here ?

2023-11-02 13:52 UTC, sairanjit commented on app/components/listItems/OrganizationListItem.tsx
> +  const orgnizationLabel = useMemo(() => organization.name, [organization])
`orgnizationLabel` change it to `organizationLabel`

2023-11-02 13:52 UTC, sairanjit commented on app/screens/OrganizationDetails.tsx
> +    credentialContainner: {
`credentialContainner` change to `credentialContainer`

2023-11-02 13:52 UTC, sairanjit commented on app/screens/OrganizationDetails.tsx
> +    orgNameContainner: {
`orgNameContainner` change to `orgNameContainer`

2023-11-02 13:52 UTC, sairanjit commented on app/screens/OrganizationDetails.tsx
> +  const fetchData = async () => {
Add this api to hooks

2023-11-02 13:52 UTC, sairanjit commented on app/screens/OrganizationDetails.tsx
> +    setOrgnizationDetailData(response?.data.org_agents)
`setOrgnizationDetailData` change to `setOrganizationDetailData`

2023-11-02 13:52 UTC, sairanjit commented on app/screens/OrganizationDetails.tsx
> +              <Text style={styles.orgHeaderText}>About Organization</Text>
Add text to localizations

2023-11-02 13:52 UTC, sairanjit commented on app/screens/OrganizationDetails.tsx
> +                <Text style={styles.orgHeaderText}>Available Credentials</Text>
Add text to localizations

2023-11-02 13:52 UTC, sairanjit commented on app/theme.ts
> +  tabsearchBackground: '#F4F4F4',
`tabsearchBackground` change to  `tabSearchBackground`

2023-11-02 13:52 UTC, sairanjit commented on app/utils/organizationHelper.ts
> +  useEffect(() => {
I think this shouldn't be handled in a useEffect instead use a util function

2023-11-02 13:52 UTC, merged