Connection interface
credebl/adeya-wallet pull request #125
Opened 2023-11-06 12:29 UTC by poonam-ghewande

### Summary 

-Added on scroll pagination for explore organisation list
-Update UI for list and  org details
-Added validation  while reconnecting  with  organisation

### Issue ticket number and link    
https://github.com/credebl/adeya-wallet/issues/122

### Checklist before requesting a review
- [x]  All commits contain a DCO Signed-off-by line (we use the DCO GitHub app to enforce this).
- [x]  Self-review of code & No unnecessary commented-out code.
- [x]  All existing functionality remain intact.
- [x]  Updated the README if necessary..
- [x]  No hard-coded sensitive information.

2023-11-06 13:44 UTC, sairanjit requested changes

2023-11-06 13:44 UTC, sairanjit commented on app/api/organizationHelper.ts
> +  }, [currentPage, pageSize])
I think `pageSize` will never change because it is constant

2023-11-06 13:44 UTC, sairanjit commented on app/components/listItems/OrganizationListItem.tsx
> +
remove commented code

2023-11-06 13:44 UTC, sairanjit commented on app/screens/OrganizationDetails.tsx
> +    if (isOrgLabelIncluded) {
use the following syntax for if/else

if (isOrgLabelIncluded) {
  ... code
  return 
}

so we can remove else here

2023-11-06 13:44 UTC, sairanjit commented on app/screens/OrganizationDetails.tsx
>          <View style={styles.orgDescriptionContainner}>
`orgDescriptionContainner` change to `orgDescriptionContainer`

2023-11-06 13:44 UTC, sairanjit commented on app/screens/OrganizationList.tsx
> +  const PAGE_SIZE = 10
move constants out of the component to `api` folder and directly use inside hook

2023-11-06 13:44 UTC, sairanjit commented on app/screens/OrganizationList.tsx
> +        <View style={styles.loder}>
`loder` change to `loader`

2023-11-06 13:44 UTC, sairanjit commented on app/screens/OrganizationList.tsx
> +                <View style={styles.loder}>
`loder` change to `loader`

2023-11-06 13:44 UTC, sairanjit commented on app/components/listItems/OrganizationListItem.tsx
>    const orgnizationLabel = useMemo(() => organization.name, [organization])
`orgnizationLabel` change to `organizationLabel`

2023-11-06 13:44 UTC, sairanjit commented on app/components/listItems/OrganizationListItem.tsx
>    const organaizationLabelAbbr = useMemo(() => orgnizationLabel?.charAt(0).toUpperCase(), [organization])
I think we don't need `useMemo` here because `organizationLabel` value is already memoized so we can directly use

```
  const organizationLabelAbbr = organizationLabel?.charAt(0).toUpperCase()
```

2023-11-07 06:28 UTC, poonam-ghewande commented on app/api/organizationHelper.ts
> +  }, [currentPage, pageSize])
done

2023-11-07 06:29 UTC, poonam-ghewande commented on app/screens/OrganizationDetails.tsx
>          <View style={styles.orgDescriptionContainner}>
done

2023-11-07 06:29 UTC, poonam-ghewande commented on app/screens/OrganizationList.tsx
> +  const PAGE_SIZE = 10
done

2023-11-07 06:29 UTC, poonam-ghewande commented on app/screens/OrganizationList.tsx
> +                <View style={styles.loder}>
done

2023-11-07 06:30 UTC, poonam-ghewande commented on app/components/listItems/OrganizationListItem.tsx
>    const organaizationLabelAbbr = useMemo(() => orgnizationLabel?.charAt(0).toUpperCase(), [organization])
done

2023-11-07 06:30 UTC, poonam-ghewande commented on app/screens/OrganizationList.tsx
> +        <View style={styles.loder}>
done

2023-11-07 07:07 UTC, poonam-ghewande commented on app/screens/OrganizationDetails.tsx
> +    if (isOrgLabelIncluded) {
done

2023-11-07 08:03 UTC, sairanjit requested changes

2023-11-07 08:03 UTC, sairanjit commented on .eslintrc.js
> +    '@typescript-eslint/no-explicit-any': 'off',
I think we can keep this rules in warning

2023-11-07 08:03 UTC, sairanjit commented on .eslintrc.js
> +    'no-unsafe-optional-chaining': 'off',
I think we can keep this rule in warning

2023-11-07 08:03 UTC, sairanjit commented on .eslintrc.js
> +      'off',
I think we need to keep this in `error` only

2023-11-07 08:03 UTC, sairanjit commented on app/api/api-constants.ts
> +export const HEADER_HEIGHT = 50
`HEADER_HEIGHT` shouldn't be in the `api-constants`. It should be in the same file outside the component.

2023-11-07 08:03 UTC, sairanjit commented on app/api/organizationHelper.ts
> +const useOrganizationData = (pageSize: number) => {
remove `pageSize` as parameter and use as constant

2023-11-07 08:03 UTC, sairanjit commented on app/components/listItems/OrganizationListItem.tsx
> +  const organaizationLabelAbbr = organizationLabel?.charAt(0).toUpperCase()
`organaizationLabelAbbr` change it to `organizationLabelAbbr`

2023-11-07 08:03 UTC, sairanjit commented on app/screens/Home.tsx
> +      <ScrollView>
I think we don't need a `ScrollView` on home screen

2023-11-07 08:03 UTC, sairanjit commented on app/screens/OrganizationDetails.tsx
>    const organaizationLabelAbbr = useMemo(() => params?.name?.charAt(0).toUpperCase(), [params])
`organaizationLabelAbbr` change to `organizationLabelAbbr`

2023-11-07 08:03 UTC, sairanjit commented on .eslintrc.js
> +      'warn',
change this to `error`

2023-11-07 08:03 UTC, sairanjit commented on app/screens/OrganizationList.tsx
>    useEffect(() => {
I think for this useEffect we don't need `return` here for `setFilteredOrganizations `

2023-11-07 09:30 UTC, poonam-ghewande commented on .eslintrc.js
> +    '@typescript-eslint/no-explicit-any': 'off',
done

2023-11-07 09:31 UTC, poonam-ghewande commented on .eslintrc.js
> +    'no-unsafe-optional-chaining': 'off',
done

2023-11-07 09:31 UTC, poonam-ghewande commented on .eslintrc.js
> +      'off',
done

2023-11-07 09:31 UTC, poonam-ghewande commented on app/api/api-constants.ts
> +export const HEADER_HEIGHT = 50
done

2023-11-07 09:31 UTC, poonam-ghewande commented on app/api/organizationHelper.ts
> +const useOrganizationData = (pageSize: number) => {
done

2023-11-07 09:31 UTC, poonam-ghewande commented on app/components/listItems/OrganizationListItem.tsx
> +  const organaizationLabelAbbr = organizationLabel?.charAt(0).toUpperCase()
done

2023-11-07 09:31 UTC, poonam-ghewande commented on app/screens/Home.tsx
> +      <ScrollView>
done

2023-11-07 09:31 UTC, poonam-ghewande commented on app/screens/OrganizationDetails.tsx
>    const organaizationLabelAbbr = useMemo(() => params?.name?.charAt(0).toUpperCase(), [params])
done

2023-11-07 09:31 UTC, poonam-ghewande commented on .eslintrc.js
> +      'warn',
done

2023-11-07 09:32 UTC, poonam-ghewande commented on app/screens/OrganizationList.tsx
>    useEffect(() => {
done

2023-11-07 09:43 UTC, sairanjit approved these changes

2023-11-07 09:43 UTC, merged