feat: google drive integration with a sign-in flow and backup upload
credebl/adeya-wallet pull request #202
Opened 2024-06-27 11:25 UTC by piyushupadhyay19

### Summary 
* Integration with @react-native-google-signin/google-signin for OAuth authentication.
* Uploading wallet backups to Google Drive using @robinbobin/react-native-google-drive-api-wrapper.

### Issue ticket number and link    
- Issue #178 

### Checklist before requesting a review
- [x]  All commits contain a DCO Signed-off-by line (we use the DCO GitHub app to enforce this).
- [x]  Self-review of code & No unnecessary commented-out code.
- [x]  All existing functionality remain intact.
- [x]  Updated the README if necessary..
- [x]  No hard-coded sensitive information.

2024-06-27 13:02 UTC, sairanjit commented
@piyushupadhyay19 Can you add the video of the feature you have completed ?

2024-06-27 17:56 UTC, piyushupadhyay19 commented
> @piyushupadhyay19 Can you add the video of the feature you have completed ?


https://github.com/credebl/adeya-wallet/assets/112110492/77d5a51e-a83b-40fe-be10-48da7cc5c819

2024-07-01 13:07 UTC, sairanjit requested changes

2024-07-01 13:07 UTC, sairanjit commented on app/contexts/auth.tsx
> +  signOut: () => Promise<void>
```suggestion
  isGoogleAccountSignedIn: boolean
  googleSignIn: () => Promise<void>
  googleSignOut: () => Promise<void>
```

2024-07-01 13:07 UTC, sairanjit commented on app/contexts/auth.tsx
> +    // await AsyncStorage.setItem('userInfo', JSON.stringify(userInfo))
- If we don't need this you can remove this

2024-07-01 13:07 UTC, sairanjit commented on app/screens/Settings.tsx
> +            })
- While signing out we can remove this toast. We can just sign-out the user

2024-07-01 13:07 UTC, sairanjit commented on app/contexts/auth.tsx
> +      const userInfo = await AsyncStorage.getItem('userInfo')
```suggestion
      const userInfo = await AsyncStorage.getItem('googleUserInfo')
```

2024-07-03 05:52 UTC, sairanjit approved these changes
LGTM

2024-07-03 10:34 UTC, merged