Export import wallet
credebl/adeya-wallet pull request #46
Opened 2023-08-11 08:17 UTC by poonam-ghewande

1. Added  Export / Import wallet  in  application

2023-08-14 06:09 UTC, sairanjitAW commented
We need to change a few flows
- Create pin screen should be after selection of (create new wallet/Import wallet)

2023-08-16 05:54 UTC, poonam-ghewande commented
Sure we will do the change in flow for (create new wallet/Import wallet) .

2023-08-17 07:51 UTC, sairanjit requested changes

2023-08-17 07:51 UTC, sairanjit commented on App.tsx
> +import { Buffer } from 'buffer'
Can we remove this as we are already using **shim.js** ?

2023-08-17 07:51 UTC, sairanjit commented on app/assets/img/backup-success1.svg
Delete this svg if not required

2023-08-17 07:51 UTC, sairanjit commented on app/assets/img/success-backup1.png
Delete this svg if not required

2023-08-17 07:51 UTC, sairanjit commented on app/navigators/RootStack.tsx
> +        <Stack.Screen name={Stacks.ContactStack} component={ContactStack} />
Please add the Navigation stacks in the appropriate location,(Notification, Connection, ... etc)

2023-08-17 07:51 UTC, sairanjit commented on app/navigators/AuthenticateStack.tsx
> +      <Stack.Screen
Add (ImportWalletVerify, ImportSuccess, CreateWallet) in appropriate stack

2023-08-17 07:51 UTC, sairanjit commented on app/screens/CreateWallet.tsx
> +    titletext: {
```suggestion
    titleText: {
```

2023-08-17 07:51 UTC, sairanjit commented on app/screens/CreateWallet.tsx
> +    subcontainer: {},
```suggestion
    }
```

2023-08-17 07:51 UTC, sairanjit commented on app/screens/CreateWallet.tsx
> +      <Text style={(TextTheme.headingTwo, styles.titletext)}>Welcome</Text>
```suggestion
      <Text style={(TextTheme.headingTwo, styles.titleText)}>Welcome</Text>
```

2023-08-17 07:51 UTC, sairanjit commented on app/screens/ExportWallet.tsx
> +    const mnemonicIndividualWordsArray: any = []
```suggestion
    const mnemonicIndividualWordsArray: string[] = []
```

2023-08-17 07:51 UTC, sairanjit commented on app/screens/ExportWalletConfirmation.tsx
> +import RNFS, { exists, mkdir, unlink, DownloadDirectoryPath } from 'react-native-fs'
remove unused imports

2023-08-17 07:51 UTC, sairanjit commented on app/screens/ExportWalletConfirmation.tsx
> +  const setPhrase = (item: string, index: number) => {
unused parameter

2023-08-17 07:51 UTC, sairanjit commented on app/screens/ImportSuccess.tsx
> +    labeltext: {
```suggestion
    labelText: {
```

2023-08-17 07:51 UTC, sairanjit commented on app/screens/ImportSuccess.tsx
> +      <Text style={(TextTheme.labelText, styles.labeltext)}>Wallet Restored successfully</Text>
```suggestion
      <Text style={(TextTheme.labelText, styles.labelText)}>Wallet Restored successfully</Text>
```

2023-08-17 07:51 UTC, sairanjit commented on app/screens/ImportWalletConfirmation.tsx
Remove unused imports

2023-08-17 07:51 UTC, sairanjit commented on app/screens/Success.tsx
> +      {/* <Text style={styles.namefiletext}>{parms?.params?.encryptedFileLocation}</Text> */}
remove commented code

2023-08-17 07:51 UTC, sairanjit commented on app/screens/Success.tsx
remove unused variables and use camelCase for all the styles

2023-08-17 07:51 UTC, sairanjit commented on app/utils/crystals-kyber.ts
Remove the crystal Kyber package

2023-08-17 07:51 UTC, sairanjit commented on app/WalletExportstyle.ts
Keep styles in the same file of the screen

2023-08-17 07:51 UTC, sairanjit commented on App.tsx
remove buffer as we are using rn-nodify

2023-08-17 07:51 UTC, sairanjit commented on package.json
remove unused dependencies

2023-08-17 13:01 UTC, poonam-ghewande commented on App.tsx
> +import { Buffer } from 'buffer'
removed Buffer from App.tsx

2023-08-17 13:01 UTC, poonam-ghewande commented on app/assets/img/backup-success1.svg
Deleted  the svg .

2023-08-17 13:02 UTC, poonam-ghewande commented on app/assets/img/success-backup1.png
Deleted the unused svg

2023-08-17 13:03 UTC, poonam-ghewande commented on app/WalletExportstyle.ts
Added styles in same screen.

2023-08-17 13:03 UTC, poonam-ghewande commented on App.tsx
removed.

2023-08-18 05:16 UTC, poonam-ghewande commented on app/navigators/AuthenticateStack.tsx
> +      <Stack.Screen
Added   (ImportWalletVerify, ImportSuccess, CreateWallet)  in setting stack.

2023-08-18 05:16 UTC, poonam-ghewande commented on app/screens/Success.tsx
removed.

2023-08-18 05:17 UTC, poonam-ghewande commented on app/utils/crystals-kyber.ts
Removed crystal kyber package.

2023-08-18 05:17 UTC, poonam-ghewande commented on package.json
Removed unused dependencies.

2023-08-18 10:11 UTC, poonam-ghewande commented on app/navigators/RootStack.tsx
> +        <Stack.Screen name={Stacks.ContactStack} component={ContactStack} />
Updated the  Navigation stack in RootStack .

2023-08-18 11:45 UTC, sairanjit approved these changes

2023-08-18 11:46 UTC, merged